version: '3.8'
services:
  teste-ipja:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    restart: always
    ports:
      - 8004:8004
    env_file:
      - stack.env
    networks:
      - pi_default
    volumes:
      - ipja2_db:/var/lib/postgresql/data
      - ipja2_app:/app/

volumes:
  ipja2_db:
  ipja2_app:

networks:
  pi_default:
    external: true
