# Generated by Django 5.1.1 on 2024-09-19 01:38

import django.core.validators
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('nascimento', models.DateField()),
                ('celular', models.CharField(max_length=11)),
                ('social', models.CharField(max_length=255)),
                ('relacao', models.CharField(choices=[('MC', 'Membro Comungante'), ('MNC', 'Membro Não Comungante'), ('CON', 'Congregado'), ('OFC', 'Oficial')], max_length=3)),
                ('sociedade', multiselectfield.db.fields.MultiSelectField(choices=[('SAF', 'SAF'), ('UPH', 'UPH'), ('UMP', 'UMP'), ('UPA', 'UPA'), ('NA', 'Nemhuma')], max_length=18)),
                ('sobre_a_igreja', models.TextField()),
                ('louvor', models.CharField(choices=[('MR', 'Muito Ruim'), ('R', 'Ruim'), ('B', 'Bom'), ('E', 'Excelente')], max_length=2)),
                ('visitacao', models.CharField(choices=[('MR', 'Muito Ruim'), ('R', 'Ruim'), ('B', 'Bom'), ('E', 'Excelente')], max_length=2)),
                ('recepcao', models.CharField(choices=[('MR', 'Muito Ruim'), ('R', 'Ruim'), ('B', 'Bom'), ('E', 'Excelente')], max_length=2)),
                ('evengelizacao', models.CharField(choices=[('MR', 'Muito Ruim'), ('R', 'Ruim'), ('B', 'Bom'), ('E', 'Excelente')], max_length=2)),
                ('comunicacao', models.CharField(choices=[('MR', 'Muito Ruim'), ('R', 'Ruim'), ('B', 'Bom'), ('E', 'Excelente')], max_length=2)),
                ('escola_dominical', models.CharField(choices=[('MR', 'Muito Ruim'), ('R', 'Ruim'), ('B', 'Bom'), ('E', 'Excelente')], max_length=2)),
                ('diaconos', models.CharField(choices=[('MR', 'Muito Ruim'), ('R', 'Ruim'), ('B', 'Bom'), ('E', 'Excelente')], max_length=2)),
                ('observacao_diaconos', models.TextField()),
                ('presbiteros', models.CharField(choices=[('MR', 'Muito Ruim'), ('R', 'Ruim'), ('B', 'Bom'), ('E', 'Excelente')], max_length=2)),
                ('observacao_presbiteros', models.TextField()),
                ('pastor', models.CharField(choices=[('MR', 'Muito Ruim'), ('R', 'Ruim'), ('B', 'Bom'), ('E', 'Excelente')], max_length=2)),
                ('observacao_pastor', models.TextField()),
                ('seu_compromisso', models.CharField(choices=[('TV', 'Tenho Vergonha'), ('PM', 'Preciso Melhorar Muito'), ('S', 'Satisfatório'), ('E', 'Excelente')], max_length=2)),
                ('leitura', models.CharField(choices=[('TV', 'Tenho Vergonha'), ('PM', 'Preciso Melhorar Muito'), ('S', 'Satisfatório'), ('E', 'Excelente')], max_length=2)),
                ('area_interesse_comunicacao', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('area_interesse_evangelismo_missoes', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('area_interesse_projeto_viver', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('area_interesse_departamento_infantil', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('area_interesse_acao_social_diaconia', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('area_interesse_visitacao', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('area_interesse_recepcao', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('area_interesse_zeladoria', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('area_interesse_eventos', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('area_interesse_pregacao', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('area_interesse_ensino', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('area_interesse_secretaria', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('area_interesse_louvor', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('dizimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
