# Generated by Django 5.1.1 on 2024-09-21 19:26

import django.core.validators
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('nascimento', models.DateField()),
                ('celular', models.CharField(max_length=11)),
                ('social', models.CharField(blank=True, default='não tem', max_length=255, null=True)),
                ('relacao', models.CharField(choices=[('Membro Comungante', 'Membro Comungante'), ('Membro Não Comungante', 'Membro Não Comungante'), ('Congregado', 'Congregado'), ('Oficial', 'Oficial')], max_length=30)),
                ('sociedade', multiselectfield.db.fields.MultiSelectField(choices=[('SAF', 'SAF'), ('UPH', 'UPH'), ('UMP', 'UMP'), ('UPA', 'UPA'), ('NA', 'Nemhuma')], max_length=18)),
                ('sobre_a_igreja', models.TextField(blank=True, default='não tem', null=True)),
                ('louvor', models.CharField(choices=[('Muito Ruim', 'Muito Ruim'), ('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], max_length=30)),
                ('visitacao', models.CharField(choices=[('Muito Ruim', 'Muito Ruim'), ('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], max_length=30)),
                ('recepcao', models.CharField(choices=[('Muito Ruim', 'Muito Ruim'), ('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], max_length=30)),
                ('evengelizacao', models.CharField(choices=[('Muito Ruim', 'Muito Ruim'), ('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], max_length=30)),
                ('comunicacao', models.CharField(choices=[('Muito Ruim', 'Muito Ruim'), ('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], max_length=30)),
                ('escola_dominical', models.CharField(choices=[('Muito Ruim', 'Muito Ruim'), ('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], max_length=30)),
                ('diaconos', models.CharField(choices=[('Muito Ruim', 'Muito Ruim'), ('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], max_length=30)),
                ('observacao_diaconos', models.TextField(blank=True, default='não tem', null=True)),
                ('presbiteros', models.CharField(choices=[('Muito Ruim', 'Muito Ruim'), ('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], max_length=30)),
                ('observacao_presbiteros', models.TextField(blank=True, default='não tem', null=True)),
                ('pastor', models.CharField(choices=[('Muito Ruim', 'Muito Ruim'), ('Ruim', 'Ruim'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], max_length=30)),
                ('observacao_pastor', models.TextField(blank=True, default='não tem', null=True)),
                ('seu_compromisso', models.CharField(choices=[('Tenho Vergonha', 'Tenho Vergonha'), ('Preciso Melhorar Muito', 'Preciso Melhorar Muito'), ('Satisfatório', 'Satisfatório'), ('Excelente', 'Excelente')], max_length=30)),
                ('leitura', models.CharField(choices=[('Tenho Vergonha', 'Tenho Vergonha'), ('Preciso Melhorar Muito', 'Preciso Melhorar Muito'), ('Satisfatório', 'Satisfatório'), ('Excelente', 'Excelente')], max_length=30)),
                ('area_interesse_comunicacao', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('area_interesse_evangelismo_missoes', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('area_interesse_projeto_viver', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('area_interesse_departamento_infantil', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('area_interesse_acao_social_diaconia', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('area_interesse_visitacao', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('area_interesse_recepcao', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('area_interesse_zeladoria', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('area_interesse_eventos', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('area_interesse_pregacao', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('area_interesse_ensino', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('area_interesse_secretaria', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('area_interesse_louvor', models.IntegerField(help_text='Escolha um número de 1 a 5 para definir a prioridade', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('dizimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_avaliacao', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrevDizimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ano', models.IntegerField()),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
