# Generated by Django 5.1.1 on 2024-09-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='social',
            field=models.CharField(blank=True, default='não tem', max_length=255, null=True),
        ),
    ]
