# Generated by Django 5.1.1 on 2024-09-21 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='area_interesse_acao_social_diaconia',
            field=models.IntegerField(blank=True, default=0, help_text='Escolha um número de 1 a 5 para definir a prioridade', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='area_interesse_comunicacao',
            field=models.IntegerField(blank=True, default=0, help_text='Escolha um número de 1 a 5 para definir a prioridade', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='area_interesse_departamento_infantil',
            field=models.IntegerField(blank=True, default=0, help_text='Escolha um número de 1 a 5 para definir a prioridade', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='area_interesse_ensino',
            field=models.IntegerField(blank=True, default=0, help_text='Escolha um número de 1 a 5 para definir a prioridade', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='area_interesse_evangelismo_missoes',
            field=models.IntegerField(blank=True, default=0, help_text='Escolha um número de 1 a 5 para definir a prioridade', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='area_interesse_eventos',
            field=models.IntegerField(blank=True, default=0, help_text='Escolha um número de 1 a 5 para definir a prioridade', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='area_interesse_louvor',
            field=models.IntegerField(blank=True, default=0, help_text='Escolha um número de 1 a 5 para definir a prioridade', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='area_interesse_pregacao',
            field=models.IntegerField(blank=True, default=0, help_text='Escolha um número de 1 a 5 para definir a prioridade', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='area_interesse_projeto_viver',
            field=models.IntegerField(blank=True, default=0, help_text='Escolha um número de 1 a 5 para definir a prioridade', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='area_interesse_recepcao',
            field=models.IntegerField(blank=True, default=0, help_text='Escolha um número de 1 a 5 para definir a prioridade', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='area_interesse_secretaria',
            field=models.IntegerField(blank=True, default=0, help_text='Escolha um número de 1 a 5 para definir a prioridade', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='area_interesse_visitacao',
            field=models.IntegerField(blank=True, default=0, help_text='Escolha um número de 1 a 5 para definir a prioridade', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='area_interesse_zeladoria',
            field=models.IntegerField(blank=True, default=0, help_text='Escolha um número de 1 a 5 para definir a prioridade', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
