# Generated by Django 5.1.1 on 2024-09-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevdizimos',
            name='ano',
            field=models.IntegerField(default='2025'),
        ),
    ]
