# Generated by Django 5.1.1 on 2024-09-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_prevdizimos_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='data_avaliacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='prevdizimos',
            name='ano',
            field=models.IntegerField(),
        ),
    ]
