# Generated by Django 5.1.1 on 2024-09-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_avaliacao_area_interesse_acao_social_diaconia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='celular',
            field=models.CharField(max_length=255),
        ),
    ]
