# Generated by Django 5.1.1 on 2024-09-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_avaliacao_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='dizimo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
