# Generated by Django 5.1.1 on 2024-09-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_avaliacao_data_avaliacao_alter_prevdizimos_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='data_avaliacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
